### ISSUE TITLE
Hellomouse moved to libera

### ISSUE THREAD

**Issue by MishaCatskill** [siraben/freenode-exodus#102]
The website refers to libera as the primary channel: https://hellomouse.net/
and here are some relevant commits from hellomouse git repos:
https://github.com/hellomouse/Athena/commit/dfa27ac4bf7651c9755039fab5ef4943949ded39
https://github.com/hellomouse/GNS/commit/cb2c503866d30d47db5feb2728d4a5acab4d9480

**Comment by wolfy1339** [comment]
As an owner of the GitHub org, I support this motion
