### ISSUE TITLE
Revolution IRC has switched to Libera

### ISSUE THREAD

**Issue by ljl-covid** [siraben/freenode-exodus#132]
[Their GitHub page](https://github.com/MCMrARM/revolution-irc) shows "A modern Android IRC client. #revolutionirc on Libera.chat", and I know due to being there that the move has happened. However, I don't have a "diff" to anything.

**Comment by pazkero** [comment]
They also updated their personal website.

Before: https://archive.is/LVAzH#70% (9 months ago)

After: https://archive.is/MWWNU#70% (right now)
