### ISSUE TITLE
Debian moved in 2009

### ISSUE THREAD

**Issue by aburch** [siraben/freenode-exodus#44]
I think it is a bit confusing to list Debian as [Debian already moved to OFTC in 2006](https://lists.debian.org/debian-devel-announce/2006/05/msg00012.html). The "#debian" channels on both Freenode and now Libera are unofficial; as far as I know there is no plan to drop the Freenode channels (yet).

**Comment by siraben** [comment]
Ok, since it was not related to recent events, I will remove it from the list. Thanks!
