### ISSUE TITLE
Clarify #lisp

### ISSUE THREAD

**Issue by phoe** [siraben/freenode-exodus#49]
The old Freenode `#lisp` (strictly Common Lisp channel) has migrated to `#commonlisp` whereas the old Freenode `##lisp` (all Lisp dialects) has migrated to `#lisp`. Maybe you could mention it like:

> #lisp (migrated to #commonlisp)
> ##lisp (migrated to #lisp)

According to our IRC logs, it seems that #sbcl (https://sbcl.sourceforge.io/) and #ccl (https://github.com/Clozure/ccl/) have also made the jump.

**Comment by siraben** [comment]
> Maybe you could mention it like:
> 
> > #lisp (migrated to #commonlisp)
> > ##lisp (migrated to #lisp)

I could do that, is there a public notice somewhere?

**Comment by phoe** [comment]
The closest I have is the topic of Freenode `#lisp` mentioning Libera Chat (where I am one of the channel operators).

```
09:11 -!- phoe [~phoe@raptor.systems] has joined #lisp
09:11 -!- Topic for #lisp: Moving to #commonlisp @ '(L i b e r a) | Welcome, traveller. 
          Look on my works, ye Mighty, and despair!
```

I wonder who can speak of Freenode `##lisp` - maybe @dlowe-net since he has founder rights of that channel on Freenode?

**Comment by dlowe-net** [comment]
Yes, I'm the founder of Freenode `##lisp`. I also suggested this name change [in a Mastodon post](https://cantos.social/@dl/106235881960998583). There is a public notice on the Common Lisp wiki regarding most of the migrations taking place: https://cliki.net/IRC
