### ISSUE TITLE
Fosshost entered (then ended) partnership with Freenode

### ISSUE THREAD

**Issue by aburch** [siraben/freenode-exodus#61]
Fosshost is listed as having left Freenode, but it might be noteworthy to mention that [Fosshost has entered a partnership with Freenode](https://fosshost.org/news/freenode).

**Comment by crabbedhaloablution** [comment]
And they made a FAQ: https://fosshost.org/news/freenode-faq
And announcement from freenode: https://freenode.net/news/fosshost-partnership
I've been reading what corwin and eth01 have written on ##freenode on Libera and they claim to still stand behind what they wrote in https://fosshost.org/news/libera-chat
I'm skeptical of the lot of them as long as they associate with freenode, though.
This comment from Hacker News illustrates how easy it is to set up an unflattering narrative about the whole situation: https://news.ycombinator.com/item?id=27371873
Until further notice, this is just something to watch I think.

**Comment by siraben** [comment]
Partnership has ended https://fosshost.org/news/freenode-partnership-to-be-discontinued 🥳
