### ISSUE TITLE
Add Fcitx, IBus

### ISSUE THREAD

**Issue by Arfrever** [siraben/freenode-exodus#63]
* Fcitx (`#fcitx`) moving to Libera.Chat:
[Commit](https://github.com/fcitx/fcitx5/commit/b491ce1589e9e6cee0adab82bfd8792e4e30260a)
[Announcement](https://groups.google.com/g/fcitx-announce/c/_OTy4QRpT2E)
* IBus (`#ibus`) moving to Libera.Chat:
[Wiki page change](https://github.com/ibus/ibus/wiki/Home/_compare/748855508c4af3051dec245e189add9813f0351d...bb997b79a0b610ead19d0123d1722826a026bced)

**Comment by crabbedhaloablution** [comment]
Heh, just committed added a PR which includes a fix for fcitx :-)
https://github.com/siraben/freenode-exodus/pull/64/commits/0fc80507d2511c1d7b0558964786c83d6b3de464
