### ISSUE TITLE
Add openSUSE

### ISSUE THREAD

**Issue by proailurus** [siraben/freenode-exodus#65]
Source:
https://lists.opensuse.org/archives/list/project@lists.opensuse.org/thread/LCFCHULXR6774YKWKX5ASKQG3ABN6B3P/

**Comment by crabbedhaloablution** [comment]
I couldn't get people on #suse  to confirm that that was the definitive announcement, but I see #suse on freenode has the Forbidden Words in /topic, so let's go with it.
