### ISSUE TITLE
Please add mGBA and TASVideos to the list.

### ISSUE THREAD

**Issue by Spikestuff** [siraben/freenode-exodus#66]
mGBA's creator endrift mentions it twice:
- https://twitter.com/endrift/status/1397410356935282689
- https://twitter.com/endrift/status/1397667565086789634

TASVideos has a thread and a news comment about moving to libera.
- http://tasvideos.org/forum/viewtopic.php?t=22647
- http://tasvideos.org/forum/viewtopic.php?p=506081#506081

**Comment by vadosnaprimer** [comment]
https://github.com/mgba-emu/www/commit/f118a6afb93fb980c744f5e748464f5dc45d18a6#diff-c0311c1df17d5d714db46ca1401ad374a35de861a461d211c6c947f1b2194034
