### ISSUE TITLE
Mesa has moved to OFTC

### ISSUE THREAD

**Issue by kaydenl** [siraben/freenode-exodus#71]
Mesa (an X.Org related project) has also moved off Freenode to OFTC:

* #dri-devel - (the main channel for Mesa development) - https://gitlab.freedesktop.org/mesa/mesa/-/commit/e6baf3777836d6d39e6e2d91c847767ca4c06c46
* #panfrost - (ARM Midgard/Bifrost/etc driver development) - https://gitlab.freedesktop.org/mesa/mesa/-/commit/e0bb2c5873419b1d4ebf97eee63007e30b5383d1
* #lima - (older ARM mali driver development) - https://gitlab.freedesktop.org/mesa/mesa/-/commit/e1e207528f3404f885d1e05e4b8fc02452fcc915
* #intel-gfx and #intel-3d (Intel driver devoplement) as well (I, Kayden, am the founder of #intel-3d and an operator on #intel-gfx) - https://gitlab.freedesktop.org/mesa/mesa/-/commit/bc1240ce94cdd4c5b0e0c9cb349ea29563fc8de5 also mentions going to OFTC for Intel graphics CI related questions - I probably should post an official email

I would suspect #radeon and #nouveau and others have moved as well, but I haven't confirmed that.  We all pretty much up and left on the same day.

Thanks for maintaining this list!

**Comment by crabbedhaloablution** [comment]
Mesa is actually already listed. I could see listing all the individual channels as an option, since arguably they are sub-projects of Mesa, but that would balloon the list by 10-20 fold since many of the other projects listed have many sub-projects.

**Comment by kaydenl** [comment]
Didn't see it when I posted this, but it's definitely there now, thanks!
