### ISSUE TITLE
Upcoming: F-Droid is moving to OFTC

### ISSUE THREAD

**Issue by IzzySoft** [siraben/freenode-exodus#78]
[F-Droid](https://f-droid.org/) is moving its channels [to OFTC](https://gitlab.com/fdroid/admin/-/issues/224#note_582451416).

**Comment by crabbedhaloablution** [comment]
I've been following that bug, but don't see yet that they have decided 100% one way or the other.

**Comment by crabbedhaloablution** [comment]
Coming soon:
https://gitlab.com/fdroid/fdroid-website/-/merge_requests/660

**Comment by IzzySoft** [comment]
Told ya. Disclosure: I'm one of the F-Droid maintainers :wink:

**Comment by Zegnat** [comment]
F-Droid posted [an official announcement](https://f-droid.org/en/2021/06/10/important-community-update.html), so I have created a PR.

**Comment by IzzySoft** [comment]
Thanks! We also announced it on Mastodon today. Matrix rooms are bridged now to OFTC as well.
